#
# Generic references
#

default_setup: &default_setup
  environment:
    - P_CLIENT_NAME: "<%= client.toLowerCase() %>"
    - P_PROJECT_NAME: "<%= project.toLowerCase() %>"
  docker:
    - image: circleci/node:carbon
  working_directory: /tmp/ginetta-ci

#
# CircleCI jobs and pipelines
#
version: 2

jobs:

  # Build the app
  build:
    <<: *default_setup

    steps:
      - checkout

      - run:
          name: Display node and npm informations
          command: |
            echo "node version $(node -v) running"
            echo "npm version $(npm -v) running"

      # Restore dependencies cache
      - restore_cache:
          keys:
            - modules-cache-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - modules-cache

      - run:
          name: Install dependencies
          command: npm install

      # Use these depending of your needs
      #- run:
      #    name: Lint check
      #    command: npm run test:lint

      #- run:
      #    name: Unit tests
      #    command: npm run test:units

      - run:
          name: Build
          command: npm run build

      - persist_to_workspace:
          root: /tmp/ginetta-ci
          paths:
            - build/*
            - .circleci/*

      - save_cache:
          paths:
            - ./node_modules
          key: modules-cache-{{ checksum "package-lock.json" }}

  deploy:
    <<: *default_setup

    steps:
      - run:
          name: Install deploy tools
          command: sudo apt install -y rsync

      - attach_workspace:
          at: /tmp/ginetta-ci

      - add_ssh_keys:
          fingerprints:
            - "e6:f9:b5:46:92:6a:e5:87:f4:c3:99:ee:a7:f1:1b:57"

      - deploy:
          name: Deploy on Staging
          command: |
            # Get Staging or Deployment informations depending of the branch
            if [ "$CIRCLE_BRANCH" == "release" ]; then
              HOST=$G_NINE_LIVE_HOST
              USER=$G_NINE_LIVE_USER
              HOMEPATH=$G_NINE_LIVE_HOMEPATH
            else
              HOST=$G_NINE_STAGING_HOST
              USER=$G_NINE_STAGING_USER
              HOMEPATH=$G_NINE_STAGING_HOMEPATH
            fi

            # Get the directory used server-side
            DIRECTORY="$P_CLIENT_NAME.ginetta.net/$P_PROJECT_NAME"
            [[ $P_CLIENT_NAME == ginetta ]] && DIRECTORY="preview.ginetta.net/$P_PROJECT_NAME"

            # And get its absolute directory
            ABSOLUTE_DIRECTORY="$HOMEPATH/$DIRECTORY/branch-circle/$CIRCLE_BRANCH/"

            bash $CIRCLE_WORKING_DIRECTORY/.circleci/deploy-rsync.sh \
              -b $CIRCLE_BRANCH \
              -s $CIRCLE_WORKING_DIRECTORY/build/ \
              -h $HOST \
              -u $USER \
              -d $ABSOLUTE_DIRECTORY

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          context: org-global
          requires:
            - build
